### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Resoluciones** [carlosdaniiel07/myeconomy-spigot#1]
Oi Carlos, parabeins pelo plugin!

Saiba que o plugin carrega OK, mais cuando vai entrar no server, e o plugin tenta se comunicar com o mysql faz crash do server, conforme detalhe:  https://hasteb.in/uvecucig.md

Vc esta com um versao funcionando OK? Me avise por gentileza!

Muito obrigado!!!!

**Comment by carlosdaniiel07** [comment]
Olá,

Primeiramente desculpa pela demora em responder. Bom, se ele crashou provavelmente foi em função de alguma falha ao estabelecer comunicação com o MySQL. Não estou conseguindo ver o conteúdo do hastebin, tem outra forma de compartilhar o erro?

Valeu!

**Comment by Resoluciones** [comment]
Olá Carlos, que estranho o hastebin sumiou!

Eu mude o plugin de economia por este erro, mais todos dam algun tipo de erro na comunicaçao com o mysql sim pelo que vejo, como Vc fala.  Eu ja avise para o host e eles estan tentando resolver.

Muito obrigado e abraçao.

**Comment by carlosdaniiel07** [comment]
Olá,

Tenta compartilhar o erro pelo [[https://pastebin.com/](url)](url) mesmo, talvez consiga lhe ajudar.

Agraço.

**Comment by Resoluciones** [comment]
O pastebin fala que excede o limite.  Veja éste link: https://hasteb.in/xikepaqe.md   Pra mi está funcionando.

**Comment by carlosdaniiel07** [comment]
Não consegui identificar a causa do problema. Você usa o Spigot no seu servidor? Você tem problemas como esse com todos os plugins que requerem conexão com o banco de dados?

**Comment by Resoluciones** [comment]
Uso Paper.  Nao com tudos, so acontece com os economy plugin.  Eu tem outros que usan mysql e sem problema.

abço

**Comment by carlosdaniiel07** [comment]
Você consegue usar o Spigot somente para testar este plugin? De qualquer maneira, vou incrementar alguns tratamentos na conexão com o banco e já subir o plugin atualizado.

**Comment by Resoluciones** [comment]
Sim posso usar un test server para isso, mais nao sei se vai dar certo para verificar o erro, ja que para o erro tem que ser um server onde tem caras jogando, e nao acontece en tudo momento, tem que estar sempre olheando a consola ou o log para detectar cuando o erro acontece.  Do contrario nao vai aparecer nada, infelizmente.

**Comment by carlosdaniiel07** [comment]
Não necessariamente. Assim que você entrar no servidor o plugin ira verificar se você possui uma "conta bancária" (isso já envolve MySQL).

**Comment by Resoluciones** [comment]
Veja aqui finalmente a explicaçao do host!!!!

I have looked over this error, and it seems pretty similar to past errors you have had- one distinct thing about your MySQL setup is that your load to our server is quite substantial, so it is worth trying a private MySQL server on a VPS Platform with specialised setup optimized to deal with your requirements.

**Comment by carlosdaniiel07** [comment]
Então pelo que entendi o seu servidor atual não está atendendo a demanda?

**Comment by Resoluciones** [comment]
sim aparentemente!

**Comment by carlosdaniiel07** [comment]
Bom, então o erro não é bem no plugin. Em breve pretendo adicionar suporte ao SQLite. Vou estar fechando esta inssue.
